name: Build Wasl Service-Prod
on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      deploy-branch:
        required: true
        default: "master"
        description: Choose Wasl branch to build
      release-tag-prefix:
        required: false
        default: "prod"
        description: Add release tag prefix

env:
  DOCKER_REGISTRY: "prod-registry.safee.com"
  DOCKER_IMAGE_NAME: "wasl"
  DOCKER_IMAGE_TAG_TEXT: "latest"
  MSTEAMS_WEBHOOK: "https://nurdernek.webhook.office.com/webhookb2/34cbc660-6cf1-43fe-b032-6ed7abd0f581@758b3098-b6f6-42ba-8309-6fb195e54bd5/IncomingWebhook/2cb79ddcab184f83b7f3a6abceba501d/b970ad1a-f46c-44ef-bda4-24c42eba2347/V2uME8lonYsh4EsLxF4mehcUOeIfCoDIXOy3AZPszg36w1"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        repository: "UgaritTech/wasl-service"
        token: ${{ secrets.PAT_TOKEN }}
        ref: ${{github.event.inputs.deploy-branch}}
        path: wasl

    - uses: actions/setup-java@v3
      with:
        distribution: 'corretto'
        java-version: '11'

    - name: Set up Maven
      uses: stCarolas/setup-maven@v4.5
      with:
        maven-version: 3.6.3

    - name: Install project artifacts (JMS)
      run: mvn install:install-file -Dfile="wasl/Artifacts/jm-connector-6.10.jar" -DgroupId="tech.ugarit" -DartifactId="jm-connector" -Dversion="6.10" -Dpackaging="jar"

    - name: Build Wasl Integration Model
      run: mvn -f wasl/wasl-integration-model/pom.xml clean install

    - name: Build Wasl Integration Management
      run: mvn -f wasl/wasl-integration-management/pom.xml clean install -DskipTests

    - name: Get latest releast tag and build timestamp
      run: |
        echo "LATEST_RELEASE_TAG=$(curl --silent -u sre-ugarit:${{ secrets.PAT_TOKEN }} https://api.github.com/repos/UgaritTech/wasl-service/tags | jq -r '.[0].name')" >> $GITHUB_ENV
        echo "BUILD_TIMESTAMP=$(date '+%Y%m%d%H%M%S')" >> $GITHUB_ENV

    - name: Login to Safee Private Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.DOCKER_REGISTRY }}
        username: sre
        password: ${{ secrets.REGISTRY_PASS }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push Wasl Docker image
      id: docker_build
      uses: docker/build-push-action@v5
      with:
        context: wasl
        push: true
        tags: ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG_TEXT }},${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:${{ github.event.inputs.release-tag-prefix }}-${{ env.LATEST_RELEASE_TAG }},${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG_TEXT }}-${{ env.BUILD_TIMESTAMP }},${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:${{ github.event.inputs.release-tag-prefix }}-${{ env.LATEST_RELEASE_TAG }}-${{ env.BUILD_TIMESTAMP }}
        cache-from: type=registry,ref=${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:buildcache
        cache-to: type=registry,ref=${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:buildcache,mode=max

    - name: Build Wasl Integration Model for hazelcast 
      run: mvn -f wasl/wasl-integration-model/pom.xml clean compile jar:jar
    - name: Build Wasl Integration Management for hazelcast 
      run: mvn -f wasl/wasl-integration-management/pom.xml clean compile jar:jar
    - name : copy to hazelcast 
      run : cp wasl/wasl-integration-model/target/wasl-integration-model-1.5.18.jar wasl/wasl-integration-cache/ |
            cp wasl/wasl-integration-management/target/wasl-integration-1.0.0.jar wasl/wasl-integration-cache/ 
            
    - name: Build and push Wasl Cache Docker image
      id: docker_build_HZ
      uses: docker/build-push-action@v5
      with:
        context: wasl/wasl-integration-cache
        push: true
        tags: ${{ env.DOCKER_REGISTRY }}/wasl-integration-cache:${{ env.DOCKER_IMAGE_TAG_TEXT }},${{ env.DOCKER_REGISTRY }}/wasl-integration-cache:${{ github.event.inputs.release-tag-prefix }}-${{ env.LATEST_RELEASE_TAG }},${{ env.DOCKER_REGISTRY }}/wasl-integration-cache:${{ github.event.inputs.release-tag-prefix }}-${{ env.LATEST_RELEASE_TAG }}-${{ env.BUILD_TIMESTAMP }}
        cache-from: type=registry,ref=${{ env.DOCKER_REGISTRY }}/wasl-integration-cache:buildcache
        cache-to: type=registry,ref=${{ env.DOCKER_REGISTRY }}/wasl-integration-cache:buildcache,mode=max

    - uses: neonidian/teams-notify-build-status@v3
      with:
        webhookUrl: ${{ env.MSTEAMS_WEBHOOK }}
        title: ${{ env.DOCKER_IMAGE_NAME }} - Prod
        status: ${{ job.status }}
        message: |
          ${{ env.DOCKER_REGISTRY }}/wasl-integration-cache:${{ github.event.inputs.release-tag-prefix }}-${{ env.LATEST_RELEASE_TAG }}-${{ env.BUILD_TIMESTAMP }}@${{ steps.docker_build_HZ.outputs.digest }}
          
          ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:${{ github.event.inputs.release-tag-prefix }}-${{ env.LATEST_RELEASE_TAG }}-${{ env.BUILD_TIMESTAMP }}@${{ steps.docker_build.outputs.digest }}

          ${{ env.DOCKER_IMAGE_NAME }} built successfully.
          
          Branch: ${{github.event.inputs.deploy-branch}}.

          Docker image ID: ${{ steps.docker_build.outputs.imageid }}.

          Docker image digest: ${{ steps.docker_build.outputs.digest }}.

          Docker image tag prefix and latest release tag: ${{ github.event.inputs.release-tag-prefix }}${{ env.LATEST_RELEASE_TAG }}.

          Timestamp: ${{ env.BUILD_TIMESTAMP }}.
      env:
        SHOULD_DISPLAY_ACTOR_LABEL: true
        SHOULD_DISPLAY_VIEW_RUN_BUTTON: true
        SHOULD_DISPLAY_VIEW_COMMIT_BUTTON: true