name: Build V-iVMS-Prod

on:
  workflow_dispatch:
    inputs:
      deploy-branch:
        required: true
        default: "master"
        description: Choose V-iVMS branch to build

  push:
    tags:
      - "*"

env:
  DOCKER_REGISTRY: "prod-registry.safee.com"
  DOCKER_IMAGE_NAME: "vivms"
  DOCKER_IMAGE_TAG_TEXT: "latest"
  MSTEAMS_WEBHOOK: "https://nurdernek.webhook.office.com/webhookb2/34cbc660-6cf1-43fe-b032-6ed7abd0f581@758b3098-b6f6-42ba-8309-6fb195e54bd5/IncomingWebhook/2cb79ddcab184f83b7f3a6abceba501d/b970ad1a-f46c-44ef-bda4-24c42eba2347/V2uME8lonYsh4EsLxF4mehcUOeIfCoDIXOy3AZPszg36w1"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        repository: "UgaritTech/V-iVMS"
        token: ${{ secrets.PAT_TOKEN }}
        fetch-depth: 0
        # If manual run, use input branch; if tag push, check out that tag
        ref: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.deploy-branch || github.ref }}
        path: vivms

    - name: Set up Java 11 (Corretto)
      uses: actions/setup-java@v3
      with:
        distribution: 'corretto'
        java-version: '11'

    - name: Set up Maven
      uses: stCarolas/setup-maven@v4.5
      with:
        maven-version: 3.6.3

    - name: Build V-iVMS
      run: mvn -f vivms/pom.xml clean install -DskipTests

    - name: Get latest tag
      id: get-latest-tag
      uses: WyriHaximus/github-action-get-previous-tag@v1
      with:
        workingDirectory: 'vivms'

    - name: Export LATEST_TAG and BUILD_TIMESTAMP
      run: |
        echo "LATEST_TAG=${{ steps.get-latest-tag.outputs.tag }}" >> $GITHUB_ENV
        echo "BUILD_TIMESTAMP=$(date '+%Y%m%d%H%M%S')" >> $GITHUB_ENV

    - name: Login to Safee Private Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.DOCKER_REGISTRY }}
        username: sre
        password: ${{ secrets.REGISTRY_PASS }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push V-iVMS Docker image
      id: docker_build
      uses: docker/build-push-action@v5
      with:
        context: vivms
        push: true
        tags: |
          ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG_TEXT }}
          ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.LATEST_TAG }}
          ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.LATEST_TAG }}-${{ env.BUILD_TIMESTAMP }}
        cache-from: type=registry,ref=${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:buildcache
        cache-to: type=registry,ref=${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:buildcache,mode=max

    - name: Send Teams notification
      uses: neonidian/teams-notify-build-status@v3
      with:
        webhookUrl: ${{ env.MSTEAMS_WEBHOOK }}
        title: ${{ env.DOCKER_IMAGE_NAME }} - Prod
        status: ${{ job.status }}
        message: |
          ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.LATEST_TAG }}-${{ env.BUILD_TIMESTAMP }}@${{ steps.docker_build.outputs.digest }}

          ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.LATEST_TAG }}@${{ steps.docker_build.outputs.digest }}

          ${{ env.DOCKER_IMAGE_NAME }} built successfully.

          Branch/Tag: ${{ github.ref_name }}.

          Docker image ID: ${{ steps.docker_build.outputs.imageid }}.
          Docker image digest: ${{ steps.docker_build.outputs.digest }}.
          Docker image latest tag: ${{ env.LATEST_TAG }}.
          Timestamp: ${{ env.BUILD_TIMESTAMP }}.
      env:
        SHOULD_DISPLAY_ACTOR_LABEL: true
        SHOULD_DISPLAY_VIEW_RUN_BUTTON: true
        SHOULD_DISPLAY_VIEW_COMMIT_BUTTON: true
