name: Get Latest Tag on Push

on:
  push:
    
    tags:
      - '*'

jobs:
  latest-tag:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout full history & all tags so we can see everything
      - name: Checkout code (full)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2. Use GraphQL-backed action to fetch the latest tag by commit date
      - name: Get latest tag
        id: get-latest
        uses: actions-ecosystem/action-get-latest-tag@v1
      
      # 3. Expose it (and a build timestamp) to subsequent steps
      - name: Export env vars
        run: |
          echo "LATEST_TAG=${{ steps.get-latest.outputs.tag }}" >> $GITHUB_ENV
          echo "BUILD_TIMESTAMP=$(date '+%Y%m%d%H%M%S')" >> $GITHUB_ENV

      # 4. (Optional) debug
      - name: Debug
        run: |
          echo "🔖 LATEST_TAG=$LATEST_TAG"
          echo "⏱ BUILD_TIMESTAMP=$BUILD_TIMESTAMP"
