name: Test Latest-Created-Tag

on:
  push:
    branches: [ main ]

jobs:
  get-tag:
    runs-on: ubuntu-latest
    steps:
      # 👇 fetch entire history + all tags
      - name: Checkout code (with all tags)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0      # pull full history
          # fetch-tags is true by default in checkout v4
          
      - name: List and pick latest-created tag
        run: |
          echo "📌 All tags (sorted by creation date):"
          git for-each-ref --sort=-creatordate \
            --format '%(refname:strip=2)' refs/tags

          LATEST_TAG=$(
            git for-each-ref --sort=-creatordate \
              --format '%(refname:strip=2)' refs/tags \
            | head -n1
          )

          echo "✅ Computed LATEST_TAG=$LATEST_TAG"
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV
          echo "BUILD_TIMESTAMP=$(date '+%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Debug env vars
        run: |
          echo "🚀 LATEST_TAG from env: $LATEST_TAG"
          echo "🚀 BUILD_TIMESTAMP from env: $BUILD_TIMESTAMP"
